# Important settings for the map
MAP_WIDTH = 100  # 80
MAP_HEIGHT = 100  # 120
LANE_WIDTH = 8  # 4.4
INITIAL_VELOCITY = 3
DELTA_T = 1  # 0.1
SIDEWALK_WIDTH = 2.0
LANE_MARKER_HEIGHT = 3.8
LANE_MARKER_WIDTH = 0.5
BUILDING_WIDTH = (MAP_WIDTH - 2*SIDEWALK_WIDTH - 2*LANE_WIDTH - LANE_MARKER_WIDTH) / 2.
TOP_BUILDING_HEIGHT = MAP_HEIGHT - (LANE_MARKER_WIDTH/2. + LANE_WIDTH + SIDEWALK_WIDTH)  # intersection_y will be subtracted
BOTTOM_BUILDING_HEIGHT = -LANE_MARKER_WIDTH/2. - LANE_WIDTH - SIDEWALK_WIDTH  # intersection_y will be added
